<a href="https://colab.research.google.com/github/Binu-Getachew/ML-Projects/blob/main/CNN_demo_by_15x15_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Important Libraries

This cell imports the necessary Python libraries for numerical operations and building neural networks:

*   **`numpy` (as `np`)**: A fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.
*   **`tensorflow` (as `tf`)**: An open-source machine learning framework developed by Google. It's used for building and training neural networks. Keras is its high-level API.
*   **`asarray` (from `numpy`)**: A function to convert input into an array.

In [171]:
import numpy as np
import tensorflow as tf
from numpy import asarray

### Seed for Reproducibility

To ensure that the "random" matrices generated are the same every time the code is run, we set a **random seed**.

*   **`np.random.seed(42)`**: This line initializes the random number generator with a fixed value (42 in this case). Any subsequent calls to NumPy's random functions will produce the same sequence of numbers if the seed is set to the same value beforehand. This is crucial for reproducible research and debugging.
*   **`data = np.random.randint(0, 20, size=(15, 15))`**: This generates a 15x15 matrix filled with random integers between 0 (inclusive) and 20 (exclusive). Because the seed was set, this `data` matrix will always be identical when this cell is executed.

In [172]:
np.random.seed(42)
data=np.random.randint(0,20,size=(15,15))

### Generate and Seed the Convolutional Kernel

Similar to the data matrix, a random seed is set before generating the convolutional kernel to ensure its reproducibility.

*   **`np.random.seed(42)`**: Ensures the random generation is reproducible.
*   **`kernel = np.random.randint(-2, 2, size=(5, 5))`**: This creates a `5x5` matrix with random integer values between -2 (inclusive) and 2 (exclusive). This matrix will serve as the **convolutional kernel** (or filter), which will be slid across the input data to perform feature extraction in the `Conv2D` layer.

In [173]:
np.random.seed(42)
kernel=np.random.randint(-2,2,size=(5,5))
print(kernel)

[[ 0  1 -2  0  0]
 [ 1 -2 -2  0 -1]
 [ 0  0  0  0  1]
 [-2  1  1  1  0]
 [-1 -2 -1  1  1]]


### Reshape Input Data for Keras `Conv2D` Layer

Keras `Conv2D` layers (and many other neural network layers) expect input data in a specific 4-dimensional format. This reshaping operation prepares the `15x15` data matrix for the model.

*   **`data = data.reshape(1, 15, 15, 1)`**:
    *   **`1` (Batch Size)**: Represents a single image (or sample) in a batch. When training or predicting with neural networks, data is often processed in batches.
    *   **`15` (Height)**: The height of the input image/feature map.
    *   **`15` (Width)**: The width of the input image/feature map.
    *   **`1` (Channels)**: The number of color channels. For grayscale images, this is 1. For RGB images, it would be 3.

This reshapes the original `(15, 15)` 2D array into a `(1, 15, 15, 1)` 4D tensor, making it compatible with the `Conv2D` layer's expected input format.

In [174]:
data = data.reshape(1,15,15,1)
print(data[0].reshape(15,15))

[[ 6 19 14 10  7  6 18 10 10  3  7  2  1 11  5]
 [ 1  0 11 11 16  9 15 14 14 18 11 19  2  4 18]
 [ 6  8  6 17  3 13 17  8  1 19 14  6 11  7 14]
 [ 2 13 16  3 17  7  3  1  5  9  3 17 11  1  9]
 [ 3 13 15 14  7 13  7 15 12 17 14 12  8 14 12]
 [ 0  6  8  0 11  7 10 18 16  7  2  2  0  4  9]
 [ 6  8  6  8  7 11  1  0 15  4  2 11  7  2  0]
 [ 2  4 14 13  2  0  4 13  6  8 14 14  9 12 18]
 [ 6 16 19  3  4  6 12 14 10  3 12  6 18  1  9]
 [12  5 11 11 19 10  6  0  0 19 12  8  2  6  5]
 [ 7  8  4  0 18  9 11 14  8 19 16 16 19 11  6]
 [ 1  2 16  4 16 16 16  1  1  4  0  0 18  1 11]
 [ 5  3 10 16  5  4 19  1  5 10 15 15  0  8  5]
 [15  2 19  3 18  2 18 19  6 19  8  0  7  6 17]
 [ 7  0 10 17  9  2  6 15 15 19 16  1  0 15 11]]


### Define the Convolutional Layer (`Conv2D`) and Model Summary

This section defines the first layer of our convolutional neural network and displays its summary.

*   **`from keras.models import Sequential`**: Imports the `Sequential` class from Keras, a linear stack of layers.
*   **`from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, Flatten`**: Imports various layer types. Here, `Conv2D` is used.
*   **`model = Sequential()`**: Initializes an empty `Sequential` model.
*   **`x = model.add(Conv2D(1,(5,5), input_shape=(15,15,1)))`**: Adds the `Conv2D` layer:
    *   **`1` (Filters)**: The layer outputs 1 feature map.
    *   **`(5,5)` (Kernel Size)**: The convolutional filter is a `5x5` matrix.
    *   **`input_shape=(15,15,1)`**: Specifies input as a `15x15` image with 1 channel.
*   **`model.summary()`**: Prints a summary showing layers, their output shapes, and the number of parameters (weights and biases) in each layer.

**`Conv2D` Output Feature Map Size Calculation (for `padding='valid'` and `strides=1`):**
When `padding='valid'` (default) and `strides=1`, the output dimension `O` from an input dimension `I` with a kernel size `K` is:
`O = I - K + 1`

For our `15x15` input and `5x5` kernel:
`Output_Height = 15 - 5 + 1 = 11`
`Output_Width = 15 - 5 + 1 = 11`
So the `Conv2D` layer will output an `11x11x1` feature map.

**Number of Parameters in `Conv2D` Layer:**
`Params = (Kernel_Height * Kernel_Width * Input_Channels + Bias) * Output_Channels`
For `Conv2D(1, (5, 5), input_shape=(15, 15, 1))`:
`Params = (5 * 5 * 1 + 1) * 1 = 26`
(The `+1` accounts for the bias term per filter.)

In [175]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, Flatten
model=Sequential()
x=model.add(Conv2D(1,(5,5), input_shape=(15,15,1)))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_58"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_57 (Conv2D)              │ (None, 11, 11, 1)      │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26 (104.00 B)

 Trainable params: 26 (104.00 B)

 Non-trainable params: 0 (0.00 B)

### Manually Set Convolutional Weights and Predict

This section demonstrates how to manually assign the pre-defined `kernel` to the `Conv2D` layer's weights and then use the model to make a prediction on the input `data`.

*   **`reshaped_kernel = kernel.reshape(5, 5, 1, 1)`**: The `kernel` (which is `5x5`) is reshaped into a 4D tensor `(Kernel_Height, Kernel_Width, Input_Channels, Output_Channels)` to match the format expected by the `set_weights()` method for a `Conv2D` layer.
*   **`weights = [reshaped_kernel, asarray([0.0])]`**: A list is created containing the reshaped kernel and a bias term (initialized to `0.0` here).
*   **`model.set_weights(weights)`**: Assigns these custom weights (kernel and bias) to the `Conv2D` layer within the `Sequential` model.
*   **`y = model.predict(data)`**: Performs a forward pass through the model using the input `data` with the assigned weights. This executes the convolutional operation followed by the max-pooling.

**Convolution Operation:**
The convolution operation involves sliding the `kernel` over the input `data`. At each position, the element-wise product of the kernel and the corresponding section of the input is summed, and then the bias is added.

`Output[x,y] = sum(Input[x+i, y+j] * Kernel[i,j] for all i,j in kernel) + Bias`

This output is then passed to the `MaxPooling2D` layer.

In [176]:
reshaped_kernel = kernel.reshape(5, 5, 1, 1)
weights = [reshaped_kernel, asarray([0.0])]

model.set_weights(weights)
y=model.predict(data)

print("Output shape:", y.shape)
print(y[0].reshape(11,11))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
Output shape: (1, 11, 11, 1)
[[ -38.  -73.  -80.  -48. -111.  -68.  -57.  -74.  -67.  -58.  -32.]
 [  -3.  -49.  -67.  -26.  -54.  -74.  -49.  -83.  -80.  -63.    3.]
 [ -69.  -50.  -24.  -58.  -19.   44.   19. -101.  -59.  -36.  -93.]
 [ -67.  -79.  -79.  -17.  -17.  -53.  -65.  -50.  -81.  -93.  -39.]
 [ -72.  -45.  -47.  -84.  -16.  -83.  -83.  -58.   14.   -6.  -40.]
 [ -14.  -38. -104.  -55.  -60.    8.   -3.  -35.  -31.  -27.  -32.]
 [ -42.  -12.    2.  -12.  -40.  -70.  -71.   -2.  -17. -132. -102.]
 [ -76.  -36.   19.  -26. -114.  -81.  -31.  -12.  -12.  -14.  -36.]
 [ -23.  -25.  -69.  -11.  -48.  -60.  -23.  -14.  -89.  -53.  -50.]
 [ -34.   -2.  -72.  -76.  -32.  -65. -106. -108.  -83.  -71.  -44.]
 [ -43.  -36. -117.  -44.  -43.   15.   17.  -76.  -91.  -65.  -59.]]


### Understanding Strides in `Conv2D` Layers

**Stride** refers to the number of pixels by which the convolutional kernel (or pooling window) shifts across the input feature map. A larger stride reduces the spatial dimensions of the output feature map, effectively downsampling it.

*   **`Conv2D(..., strides=(2, 2), ...)`**: `strides=(Sx, Sy)`: `Sx` is the step size for moving horizontally, and `Sy` is the step size for moving vertically. Here, a stride of `(2, 2)` means the kernel moves 2 pixels at a time both horizontally and vertically.

**Output Feature Map Size Calculation with Strides (for `padding='valid'`):**
`Output_Dimension = floor((Input_Dimension - Kernel_Dimension) / Stride) + 1`

For a `15x15` input and a `5x5` kernel with `strides=(2, 2)`:
`Output_Height = floor((15 - 5) / 2) + 1 = floor(10 / 2) + 1 = 5 + 1 = 6`
`Output_Width = floor((15 - 5) / 2) + 1 = floor(10 / 2) + 1 = 5 + 1 = 6`
So, this `Conv2D` layer would output a `6x6x1` feature map.

In [177]:
model=Sequential()
x=model.add(Conv2D(1,(5,5), strides=(2,2) ,input_shape=(15,15,1)))
model.summary()
model.set_weights(weights)
y=model.predict(data)

print("Output shape:", y.shape)
print(y[0].reshape(6,6))

Model: "sequential_59"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_58 (Conv2D)              │ (None, 6, 6, 1)        │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26 (104.00 B)

 Trainable params: 26 (104.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
Output shape: (1, 6, 6, 1)
[[ -38.  -80. -111.  -57.  -67.  -32.]
 [ -69.  -24.  -19.   19.  -59.  -93.]
 [ -72.  -47.  -16.  -83.   14.  -40.]
 [ -42.    2.  -40.  -71.  -17. -102.]
 [ -23.  -69.  -48.  -23.  -89.  -50.]
 [ -43. -117.  -43.   17.  -91.  -59.]]


### Understanding Padding in `Conv2D` Layers

**Padding** refers to adding extra pixels (typically zeros) around the border of the input image. This is often done to control the spatial dimensions of the output feature map.

*   **`padding='valid'` (Default)**: No padding is added. The kernel only slides over valid regions of the input. This typically results in an output feature map that is smaller than the input.
*   **`padding='same'`**: Padding is added to the input (usually zeros) such that the output feature map has the *same* spatial dimensions as the input, assuming a stride of 1. If `strides > 1`, the output dimensions will be `ceil(Input_Dimension / Stride)`.

*   **`Conv2D(..., padding='same', ...)`**: With `padding='same'`, the layer adds enough zero-padding to the input image such that the output feature map has the same height and width as the input when `strides=1`.

**Output Feature Map Size Calculation with `padding='same'`:**
For `padding='same'` and `strides=1`:
`Output_Dimension = Input_Dimension`

For `padding='same'` and `strides=S`:
`Output_Dimension = ceil(Input_Dimension / S)`

For a `15x15` input and a `5x5` kernel with `padding='same'` and default `strides=1`:
`Output_Height = 15`
`Output_Width = 15`
So, this `Conv2D` layer would output a `15x15x1` feature map.

In [178]:
model=Sequential()
x=model.add(Conv2D(1,(5,5), padding='same' ,input_shape=(15,15,1)))
model.summary()
model.set_weights(weights)
y=model.predict(data)

print("Output shape:", y.shape)
print(y[0].reshape(15,15))


Model: "sequential_60"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_59 (Conv2D)              │ (None, 15, 15, 1)      │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26 (104.00 B)

 Trainable params: 26 (104.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Output shape: (1, 15, 15, 1)
[[  23.   25.   19.   23.   19.   17.  -21.   -7.   22.    8.  -15.  -28.
    -8.  -35.  -21.]
 [  26.  -27.  -56.  -40.  -31.  -53.  -33.  -35.  -22.   19.   30.  -49.
   -28.  -33.  -54.]
 [  21.   13.  -38.  -73.  -80.  -48. -111.  -68.  -57.  -74.  -67.  -58.
   -32.  -57. -101.]
 [  26.   -8.   -3.  -49.  -67.  -26.  -54.  -74.  -49.  -83.  -80.  -63.
     3.  -23.  -70.]
 [  -3.  -21.  -69.  -50.  -24.  -58.  -19.   44.   19. -101.  -59.  -36.
   -93.  -28.  -28.]
 [  13.  -31.  -67.  -79.  -79.  -17.  -17.  -53.  -65.  -50.  -81.  -93.
   -39.  -62. -124.]
 [  27.  -13.  -72.  -45.  -47.  -84.  -16.  -83.  -83.  -58.   14.   -6.
   -40.  -49.  -53.]
 [  22.   -1.  -14.  -38. -104.  -55.  -60.    8.   -3.  -35.  -31.  -27.
   -32.  -12.  -56.]
 [  11.  -22.  -42.  -12.    2.  -12.  -40.  -70.  -71.   -2.  -17. -132.
  -102.  -87.  -89.]
 [   8.   -7.  -76.  -36.   19.  -26. -114.  -81.  -31.  -12.  -12.  -14.
   -

### MaxPooling Layer

**MaxPooling** is a downsampling operation commonly used in convolutional neural networks. Its main purposes are to:
1.  Reduce the spatial dimensions (height and width) of the feature maps.
2.  Reduce the number of parameters and computation in the network.
3.  Provide translational invariance to small shifts in the input.

*   **`MaxPooling2D((pool_size=(2,2)))`**: Defines the size of the pooling window (a `2x2` region). If `strides` is not specified, it defaults to `pool_size` (e.g., `strides=(2,2)`).

The `MaxPooling2D` layer works by taking the maximum value within each `pool_size` window as it slides across the input feature map (determined by `strides`).

**Output Feature Map Size Calculation for `MaxPooling2D`:**
`Output_Dimension = floor((Input_Dimension - Pool_Size) / Stride) + 1`

Given an input feature map to `MaxPooling2D`:
For example, if the `Conv2D` layer outputs a `6x6` feature map, and this `6x6` output then becomes the input to `MaxPooling2D` with `pool_size=(2,2)` and `strides=(2,2)`:
`Output_Height = floor((6 - 2) / 2) + 1 = floor(4 / 2) + 1 = 2 + 1 = 3`
`Output_Width = floor((6 - 2) / 2) + 1 = floor(4 / 2) + 1 = 2 + 1 = 3`
So, this sequence of layers would output a `3x3x1` feature map.

In [179]:
model=Sequential()
x=model.add(Conv2D(1,(5,5), strides=(2,2) ,input_shape=(15,15,1)))
model.add(MaxPooling2D((2,2)))
model.summary()
model.set_weights(weights)
y=model.predict(data)

print("Output shape:", y.shape)
print(y[0].reshape(3,3))

Model: "sequential_61"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_60 (Conv2D)              │ (None, 6, 6, 1)        │            26 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_12 (MaxPooling2D) │ (None, 3, 3, 1)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26 (104.00 B)

 Trainable params: 26 (104.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
Output shape: (1, 3, 3, 1)
[[-24.  19. -32.]
 [  2. -16.  14.]
 [-23.  17. -50.]]


### AveragePooling2D Layer

**AveragePooling2D** is another type of downsampling operation, similar to MaxPooling2D. Instead of taking the maximum value within a pooling window, it calculates the *average* value.

Its main purposes are also to:
1.  Reduce the spatial dimensions (height and width) of the feature maps.
2.  Reduce the number of parameters and computation in the network.
3.  Provide a form of noise reduction and make the representation more robust to variations.

*   **`AveragePooling2D((pool_size=(2,2)))`**: Defines the size of the pooling window (a `2x2` region). Similar to MaxPooling2D, if `strides` is not specified, it defaults to `pool_size` (e.g., `strides=(2,2)`).

The `AveragePooling2D` layer works by calculating the average value within each `pool_size` window as it slides across the input feature map (determined by `strides`).

**Output Feature Map Size Calculation for `AveragePooling2D`:**
The formula is identical to MaxPooling2D:
`Output_Dimension = floor((Input_Dimension - Pool_Size) / Stride) + 1`

Given the preceding `Conv2D(1,(5,5), strides=(2,2), input_shape=(15,15,1))` layer:
The `Conv2D` layer outputs a `6x6` feature map. This `6x6` output then becomes the input to `AveragePooling2D`.

For a `6x6` input to `AveragePooling2D` with `pool_size=(2,2)` and `strides=(2,2)`:
`Output_Height = floor((6 - 2) / 2) + 1 = floor(4 / 2) + 1 = 2 + 1 = 3`
`Output_Width = floor((6 - 2) / 2) + 1 = floor(4 / 2) + 1 = 2 + 1 = 3`
So, this sequence of layers would output a `3x3x1` feature map.

In [180]:
model=Sequential()
x=model.add(Conv2D(1,(5,5), strides=(2,2) ,input_shape=(15,15,1)))
model.add(AveragePooling2D((2,2)))
model.summary()
model.set_weights(weights)
y=model.predict(data)

print("Output shape:", y.shape)
print(y[0].reshape(3,3))

Model: "sequential_62"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_61 (Conv2D)              │ (None, 6, 6, 1)        │            26 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_15            │ (None, 3, 3, 1)        │             0 │
│ (AveragePooling2D)              │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26 (104.00 B)

 Trainable params: 26 (104.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
Output shape: (1, 3, 3, 1)
[[-52.75 -42.   -62.75]
 [-39.75 -52.5  -36.25]
 [-63.   -24.25 -72.25]]


### Flatten Layer

The **`Flatten()`** layer is used to transform the multi-dimensional output of convolutional or pooling layers into a 1-dimensional array (vector). This is a crucial step when transitioning from convolutional layers to fully connected (dense) layers in a neural network, as dense layers typically expect a 1D input.

*   **How it works**: It takes the input feature map (e.g., `(batch_size, height, width, channels)`) and flattens it into a single vector of shape `(batch_size, height * width * channels)`. It does not introduce any learnable parameters.

**Output Shape Calculation for `Flatten` Layer:**
`Output_Shape = Input_Height * Input_Width * Input_Channels`

For example, if the output from a preceding `AveragePooling2D` layer is `(batch_size, 3, 3, 1)`, a `Flatten()` layer would transform it to `(batch_size, 3 * 3 * 1)`, which is `(batch_size, 9)`.

In [181]:
model=Sequential()
x=model.add(Conv2D(1,(3,3), strides=(2,2) ,input_shape=(15,15,1)))
model.add(AveragePooling2D((2,2)))
model.add(Flatten())
model.summary()

Model: "sequential_63"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_62 (Conv2D)              │ (None, 7, 7, 1)        │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_16            │ (None, 3, 3, 1)        │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 9)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10 (40.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)